### ISSUE TITLE
Add more instructions for LDAPS

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Broadsea#75]
As described in #74 , there's a keytool step needed to generate the cacerts file that isn't clear in the readme.

**Comment by gkowalski** [comment]
So my time is not a total waste here is the instructions I used to create a cacerts 

https://stackoverflow.com/questions/11617210/how-to-properly-import-a-selfsigned-certificate-into-java-keystore-that-is-avail

$ echo -n |  openssl s_client -starttls ldap -connect  ourdomain.net:389 |   sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > ./cert_proxy_ldap.crt

Test it 

$  openssl x509 -in cert_proxy_ldap.crt -text

copy this crt file to my local mac running jdk 1.8 : 

$ keytool -import -trustcacerts -keystore ./cacerts -storepass changeit -noprompt -alias mycert -file   cert_proxy_ldap.crt

copy the generated cacerts back to my docker server/  into the Broadsea dir over the cacerts file . 

Out instance still does not work , and it connects to ldap:// but not ldaps://  , Still cannot log in so there is something else amiss in our config. 

G

**Comment by gkowalski** [comment]
Don't try to copy the cert file to the running 

even with making the filesystem read/write (   read_only: false ) : 
```
 ohdsi-webapi:
    container_name: ohdsi-webapi
    platform: ${DOCKER_ARCH}
    restart: unless-stopped
    ipc: none
    read_only: false
....
```

one gets a IOException , spent alot of time on this "easy" task .
